######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 7 18:54:37 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QtTestComponentManager.h \
           QtTestNetworkInterfaceStatus.h \
           QtTestFrame.h
SOURCES += main.cpp \
           QtTestComponentManager.cpp \
           QtTestNetworkInterfaceStatus.cpp \
           QtTestFrame.cpp
QT += network
